[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "aoc_2025"
version = "0.1.1"
requires-python = ">=3.10"
dependencies = [
    "intervaltree",
    "numpy",
    "requests"
]

[tool.setuptools.packages.find]
where = ["src"]